### Pytorch introduction



In [77]:
# pip3 install torch torchvision torchaudio

In [78]:
import torch

In [79]:
## check cuda
print(torch.cuda.is_available())

False


### Tensors

multidimensional array, with capabilities with gpu operations

In [80]:
## 1 scaler Tensor zero dimension

a=2
scaler =torch.tensor(24) 
print("scaler Tensor is :", scaler)
print("scaler Tensor Dimension :", scaler.ndim)
print("scaler Tensor shape :", scaler.shape) ## empty

scaler Tensor is : tensor(24)
scaler Tensor Dimension : 0
scaler Tensor shape : torch.Size([])


In [81]:
## 1D tensor : Vector

vector =torch.tensor([12,3,4])
print("Vector Tensor is :", vector)
print("Vector Tensor Dimension :", vector.ndim)
print("Vector Tensor Shape:", vector.shape) ## shape of the matrix or vector in the []

Vector Tensor is : tensor([12,  3,  4])
Vector Tensor Dimension : 1
Vector Tensor Shape: torch.Size([3])


In [ ]:
## 2D tensor : Vector

matrix2d =torch.tensor(
    [
    [12.,3,4], 
    [12,345.,6]
    ]
    ) ## doing it for better understanding
print("matrix Tensor is :", matrix2d)
print("matrix Tensor Dimension :", matrix2d.ndim) ## 2 1d vector inside the [] bracket
print("matrix Tensor Shape:", matrix2d.shape) ## shape of the matrix or vector in the []

matrix Tensor is : tensor([[ 12.,   3.,   4.],
        [ 12., 345.,   6.]])
matrix Tensor Dimension : 2
matrix Tensor Shape: torch.Size([2, 3])


In [83]:
## 3D tensor 

matrix =torch.tensor(
    [
    [
    [12,3,4], 
    [12,345,6],
    ],
    [
    [12,3,4], 
    [12,345,6],
    ]
    ]
    ) ## doing it for better understanding
print("matrix Tensor is :", matrix)
print("matrix Tensor Dimension :", matrix.ndim) ## 2 1d vector inside the [] bracket
print("matrix Tensor Shape:", matrix.shape) ## shape of the matrix or vector in the [] 
## output [2,2,2] we have two 2,2x2 matrix 

matrix Tensor is : tensor([[[ 12,   3,   4],
         [ 12, 345,   6]],

        [[ 12,   3,   4],
         [ 12, 345,   6]]])
matrix Tensor Dimension : 3
matrix Tensor Shape: torch.Size([2, 2, 3])


In [86]:
## GPU accleration

if torch.cuda.is_available():
    gpu_tensor =vector.to('cuda')
    print(gpu_tensor)
else:
    print('cuda is not available')



cuda is not available


In [93]:
## Tensor Properties

print("data type of matrix", matrix.dtype)

print("Device of tensor", matrix.device)
# print("Device of tensor", gpu_tensor.device) ## cuda is not available

print("is tensor on GPU:", matrix.is_cpu) ## is_cuda

print("size", matrix.size())

print("num of element", matrix.numel())

data type of matrix torch.int64
Device of tensor cpu
is tensor on GPU: True
size torch.Size([2, 2, 3])
num of element 12


In [107]:
## Accessing elements in a tensor

'''
tensor[row, column]
'''

te=torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print("dimension :", te.ndim)
print(te.shape)
print(te)
print(te[0,0])

dimension : 2
torch.Size([3, 3])
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor(10)


In [130]:
print("zeroth row" ,te[0]) ## zeroth row
print("2nd row",te[2]) ## the 2nd row 

print("zeroth column",te[:,0])

print("last column",te[:,-1]) ## last column

print("\ntill the last column and all the rows:\n",te[:,:-1]) ## till the last column and all the rows

print("\n all column and all the rows:\n",te[:,:])

zeroth row tensor([10, 20, 30])
2nd row tensor([70, 80, 90])
zeroth column tensor([10, 40, 70])
last column tensor([30, 60, 90])

till the last column and all the rows:
 tensor([[10, 20],
        [40, 50],
        [70, 80]])

 all column and all the rows:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
