In [ ]:
import torch

In [11]:
random_tensor = torch.rand(5)
print(random_tensor)
print(random_tensor.ndim)

tensor([0.0940, 0.6160, 0.4351, 0.2634, 0.3913])
1


In [21]:
random_tensor1 = torch.rand(2,5,3) ## 2 of 5x3 matrix
print(random_tensor1)
print(random_tensor1.ndim)

tensor([[[0.2660, 0.6805, 0.7001],
         [0.5361, 0.9686, 0.4374],
         [0.4041, 0.7156, 0.5867],
         [0.6035, 0.8783, 0.0709],
         [0.9092, 0.8253, 0.5595]],

        [[0.3549, 0.1518, 0.7811],
         [0.6699, 0.1343, 0.9328],
         [0.1207, 0.9876, 0.7978],
         [0.4795, 0.9464, 0.6356],
         [0.4103, 0.7993, 0.0794]]])
3


In [69]:
torch.manual_seed(5) ##  reproducibility keep it same
random_tensor1 = torch.rand(2,5,3) ## 2 of 5x3 matrix
print(random_tensor1)
print(random_tensor1.ndim)
print(random_tensor1.shape)

tensor([[[0.8303, 0.1261, 0.9075],
         [0.8199, 0.9201, 0.1166],
         [0.1644, 0.7379, 0.0333],
         [0.9942, 0.6064, 0.5646],
         [0.0724, 0.6593, 0.7150]],

        [[0.5793, 0.9809, 0.6502],
         [0.0566, 0.9201, 0.6698],
         [0.2615, 0.0407, 0.7850],
         [0.9752, 0.0903, 0.5273],
         [0.6794, 0.2639, 0.3906]]])
3
torch.Size([2, 5, 3])


In [ ]:
## Generate Random Integer
'''
torch.randint(low, high, size)
'''

rand_int=torch.randint(4,15,(5,2,2)) ## there are 5 2x2 matrix
print(rand_int)

tensor([[[12,  6],
         [ 4,  4]],

        [[14, 13],
         [12,  9]],

        [[ 4, 12],
         [11, 11]],

        [[11,  6],
         [13,  4]],

        [[ 8,  6],
         [ 4, 11]]])


In [83]:
random_tensor1 = torch.rand(10,1,2) ## 2 of 5x3 matrix
print(random_tensor1)

tensor([[[0.0137, 0.0703]],

        [[0.2800, 0.4589]],

        [[0.5100, 0.3637]],

        [[0.7462, 0.4670]],

        [[0.0892, 0.6457]],

        [[0.8794, 0.6628]],

        [[0.6223, 0.6830]],

        [[0.7003, 0.7331]],

        [[0.9869, 0.4404]],

        [[0.4665, 0.0638]]])


ModuleNotFoundError: No module named 'sklearn'